unified_mode     'true'
name             'rbcgroup'
maintainer       'Miguel Álvarez'
maintainer_email 'malvarez@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-cgroup'
version          '0.0.2'
