unified_mode     'true'
name             'rbcgroup'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-rb-cgroup'
version          '2.0.1'
